services:
  db:
    image: pgvector/pgvector:pg17
    hostname: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  inngest:
    image: inngest/inngest:latest
    ports:
      - "8288:8288"
    command:
      - /usr/bin/inngest
      - dev
      - --host
      - 0.0.0.0
      - -u
      - http://host.docker.internal:3000/api/inngest

    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:
